regenesis/views/catalog.py
from flask import Blueprint, render_template

from regenesis.core import app, engine, get_catalog
from regenesis.views.util import dimension_type_text
from regenesis.database import statistic_table, dimension_table

blueprint = Blueprint('catalog', __name__)


@blueprint.route('/<catalog>/index.html')
def view(catalog):
    catalog = get_catalog(catalog)
    statistics = statistic_table.find(order_by='title_de')
    dimensions = []
    for dimension in dimension_table.find(order_by='title_de'):
        dimension['measure_type_name'] = dimension_type_text(dimension['measure_type'])
        dimensions.append(dimension)

    return render_template('catalog/index.html',
                           catalog=catalog,
                           statistics=statistics,
                           dimensions=dimensions)

regenesis/views/dimension.py
from flask import Blueprint, render_template
from sqlalchemy import func, select, and_

from regenesis.core import app, engine, get_catalog
from regenesis.database import dimension_table, value_table
from regenesis.database import cube_table, statistic_table, reference_table

blueprint = Blueprint('dimension', __name__)

def get_statistics(dimension_name=None):
    ct = cube_table.table.alias('cube')
    st = statistic_table.table.alias('statistic')
    rt = reference_table.table.alias('reference')
    tables = [ct, st, rt]
    wheres = [
      st.c.name==ct.c.statistic_name,
      rt.c.cube_name==ct.c.name,
      rt.c.dimension_name==dimension_name
      ]
    q = select([st], and_(*wheres), tables, distinct=True)
    return list(engine.query(q))

@blueprint.route('/<catalog>/dimensions/<name>.html')
def view(catalog, name):
    catalog = get_catalog(catalog)
    dimension = dimension_table.find_one(name=name)
    values = list(value_table.find(dimension_name=name, order_by='title_de'))
    has_values = len(values) > 0
    statistics = get_statistics(name)
    return render_template('dimension/view.html',
                           catalog=catalog,
                           statistics=statistics,
                           values=values,
                           has_values=has_values,
                           dimension=dimension)

regenesis/views/statistic.py
import re
from flask import Blueprint, render_template
from collections import defaultdict

from regenesis.core import app, engine, get_catalog
from regenesis.views.util import dimension_type_text
from regenesis.database import statistic_table, cube_table
from regenesis.queries import get_dimensions
from regenesis.views.util import parse_description

blueprint = Blueprint('statistic', __name__)

ADM_RANKS = {
    'gemein': 1,
    'kreise': 2,
    'regbez': 3,
    'dland': 4,
    'dinsg': 5
}

def make_keywords(titles):
    keywords = set()
    for t in titles:
        t = re.sub('\(.*\)', '', t)
        for s in re.split('[\s\.\/]', t):
            s = s.strip()
            if not len(s) > 2 or s[0] != s[0].upper():
                continue
            keywords.add(s)
    return ', '.join(keywords)

def get_cubes(statistic_name=None):
    q = cube_table.table.select()
    q = q.where(cube_table.table.c.statistic_name==statistic_name)
    return list(engine.query(q))


@blueprint.route('/<catalog>/statistics/<slug>.<name>.html')
def view(catalog, slug, name):
    catalog = get_catalog(catalog)
    statistic = statistic_table.find_one(name=name)
    desc = parse_description(statistic['description_de'] or '')
    cubes = []
    dims = defaultdict(int)
    titles = set([statistic['title_de']])
    for cube in get_cubes(name):
      cube['dimensions'] = get_dimensions(cube['name'])
      for dim in cube['dimensions']:
        dim['show'] = True
        dims[dim['dim_name']] += 1
        titles.add(dim['dim_title_de'])
        dim['type_text'] = dimension_type_text(dim['dim_measure_type'])
        if dim['dim_measure_type'].startswith('K-REG'):
            cube['admlevel'] = (ADM_RANKS[dim['dim_name']], dim['dim_title_de'], dim['dim_name'])
            dim['show'] = False
      cube['stand'] = cube['provenance'].split('hat am')[-1].split('um')[0].strip()
      cubes.append(cube)
    common = [d for d, i in dims.items() if i == len(cubes)]
    commons = {}
    for cube in cubes:
        for dim in cube['dimensions']:
            if dim['dim_name'] in common and dim['show']:
                #dim['show'] = False
                commons[dim['dim_name']] = dim

    keywords = make_keywords(titles)
    description = desc.get('method', '')[:150]
    return render_template('statistic/view.html',
                           catalog=catalog,
                           desc=desc,
                           cubes=cubes,
                           keywords_text=keywords,
                           description_text=description,
                           common=commons.values(),
                           has_common=len(common) > 0,
                           statistic=statistic)

regenesis/views/util.py
import re

SPLITTER = re.compile('\n(\d.*):\s', re.M)

def dimension_type_text(type_name):
    if type_name.startswith('ZI-MM'):
        return 'Zeitattribut'
    if type_name.startswith('K-REG'):
        return 'Geographisches Attribut'
    if type_name.startswith('K-SACH'):
        return 'Sachattribut'
    if type_name.startswith('W-MM'):
        return 'Messwert'
    return type_name


def parse_description(description):
    description = '\n' + description
    parts = SPLITTER.split(description)[1:]
    data = {'method': 'Keine Angaben.', 'type': 'Keine Angaben.'}
    for i in range(0, len(parts), 2):
        section, text = parts[i], parts[i+1].strip()
        if 'Art der Statistik' in section:
            data['type'] = text
        elif 'Rechtsgrundlage' in section:
            data['legal'] = text
        elif 'Bereitstellung' in section:
            data['periodicity'] = text
        elif 'Stichtag' in section:
            data['stag'] = text
        elif 'Regionalebene' in section:
            data['geo'] = text
        elif 'Methodische' in section:
            data['method'] = text
    return data

regenesis/templates/api.html
{%extends "layout.html" %}

{% block description %}JSON-basierte API (Programmierschnittstelle) für die statistischen Daten von Bund und Ländern.{% endblock %}

{% block keywords %}API, JSON, Statistik, Regionalstatistik, Daten{% endblock %}

{% block title %}API (Programmierschnittstelle){% endblock %}

{% block content %}
    <h2 class="page-title">API (Programmierschnittstelle)</h2>
    <div class="row">
      <div class="col-12 col-sm-12 col-lg-6 content">
        <h3>Einfach auf die ReGENESIS-Daten zugreifen</h3>
        <p>
            ReGENESIS verfügt über eine Programmierschnittstelle, die dynamisch
            Daten aus den verschiednenen Statistiken als JSON zur Verfügung
            stellt. Die Schnittstelle unterstützt das Filtern und Gruppieren
            der Daten nach allen enthaltenen Attributen. So können aus einer 
            Tabelle etwa alle Werte eines bestimmten Jahres gefiltert, und dann 
            nach Kreis aggregiert werden.
        </p>
        <p>
            Daten aus der ReGENESIS-API können in interaktiven Visualisierungen
            genutzt werden, sodass diese stets aktuelle Werte ausweisen. Die 
            Ergebnisse der API werden gecached, um eventuelle Lastspitzen durch 
            eine Verlinkung auf vielbesuchten Seiten abzufangen. 
        </p>
        
        <h3>Basierend auf "Cubes"</h3>
        <p>
            Die ReGENESIS-API basiert auf dem freien Softwarepaket <a href="http://cubes.databrewery.org/index.html">Cubes</a>,
            einer Komponente der <a href="http://databrewery.org/">DataBrewery</a>.
        </p>
        <p>
            <strong>Die vollständige Dokumentation der HTTP-API von Cubes ist auf 
            der Webseite des Projekts <a href="http://pythonhosted.org/cubes/server.html">verfügbar</a>.</strong>
        </p>
        <h3>Sag Hallo</h3>
        <p>
            Falls Sie die API von ReGENESIS in Ihren Projekten nutzen, dann 
            teilen Sie uns das gerne mit! Wir würden gerne erfahren, wie und 
            wofür dieses Angebot genutzt wird. 
        </p>
        <code>friedrich@pudo.org</code>
      </div>

      <div class="col-12 col-sm-12 col-lg-6 content">
        <h3>Anwendungsbeispiel</h3>
        <p>
            Zur Nutzung der API können die Endpunkte genutzt werden, die auf 
            den Infoseiten zu einzelnen Statistiken verfügbar sind. Neben der
            <a href="http://pythonhosted.org/cubes/server.html">Dokumentation der HTTP-API</a> hier einige Beispiele,
            die auf der <a href="/regional/statistics/insolvenzstatistik.52411.html">Insolvenzstatistik (52411)</a>
            basieren. Alle verfügbaren Attribute und Messwerte sind auf der 
            Infoseitezur Statistik ausgewiesen. Die URL des Endpunkts ist:
        </p>
        <p>
            <a href="http://api.regenesis.pudo.org/cube/52411kj002/aggregate">
                <code>http://api.regenesis.pudo.org/cube/52411kj002/aggregate</code></a>
        </p>
        <p>
            Ruft man ihn direkt auf, so erhält man eine JSON-Antwort mit einem
            <code>summary</code>-Objekt. Dieses weist die Summe aller Insolvenzen
            (<code>isv001_sum</code>) und die Gesamtzahl der Datenzeilen (15702)
            aus.
        </p>
        <p>
            Mit dem <code>cut</code>-Parameter können die Einträge gefiltert werden.
            Die Insolvenzstatistik verfügt über ein <code>jahr</code>-Attribut, 
            welches mit dem folgenden Query auf das Jahr 2011 eingegrenzt werden kann:
        </p>
        <p>
            <code>.../aggregate?cut=jahr.text:2011</code>
        </p>
        <p>
            Neben dem <code>jahr</code> können wir auch andere Attribute filtern, 
            etwa die Art des Verfahrens (Attribut <code>isvat3</code>):
        </p>
        <p>
            <a href="http://api.regenesis.pudo.org/cube/52411kj002/aggregate?cut=jahr.text:2011|isvat1.name:isvart01">
                <code>.../aggregate?cut=jahr.text:2011|isvat1.name:isvart01</code></a>
        </p>
        <p>
            Das <code>summary</code>-Objekt in der Antwort weist nun nur noch 413
            Zeilen aus: eine Insolvenzstatistik für jeden Kreis. Zur Darstellung, 
            z.B. auf einer Karte, wollen wir diese Kreise einzeln ausgewiesen haben.
            Dazu ist der <code>drilldown</code>-Parameter geeignet:
        </p>
        <p>
            <a href="http://api.regenesis.pudo.org/cube/52411kj002/aggregate?cut=jahr.text:2011|isvat1.name:isvart01&drilldown=kreise">
                <code>.../aggregate?cut=jahr.text:2011|isvat1.name:isvart01<br>&amp;drilldown=kreise</code></a>
        </p>
        <p>
            Die Antwort enthält nun neben der <code>summary</code> ein <code>cells</code>-Objekt, in 
            dem für jeden Kreis dessen Name, AGZ und die Zahl der eröffneten Insolvenzverfahren
            ausgewiesen ist.
        </p>
        <p>
            Neben den hier vorgestellten Optionen können auch Paginierung und Sortierung 
            beeinflusst werden. Mehr Informationen dazu enthält die
            <a href="http://pythonhosted.org/cubes/server.html#http-api">Dokumentation</a>.
        </p>
      </div>
  </div>

{% endblock %}

regenesis/templates/catalog/index.html
{%extends "layout.html" %}

{% block title %}{{ catalog.title }}{% endblock %}

{% block metatitle %}{{ catalog.title }}{% endblock %}

{% block content %}
  <div id="page" class="row content">
    <div class="col-12">
      <p>
        ReGenesis stellt die Statistiken der bundesweiten <a href="https://www.regionalstatistik.de/genesis/online/logon">Regionalstatistik</a> in einfachen,
        zur maschinellen und journalistischen Weiterverabeitung geeigneten Formaten zur
        Verfügung. <a href="/faq.html">Mehr...</a>
      </p>
    </div>

    <h2 class="col-12"><i class="icon-th"></i> Statistiken</h2>
    <p class="col-12">
      Statistiken beschreiben die einzelnen Messreihen, die von den Ämtern erhoben werden. Die 
      erfassten Daten werden dann in verschiedenen Fassungen mit unterschiedlichen Attributen 
      (sogenannten Quadern) bereit gestellt.
    </p>
    <div class="col-12 row">
      {% for statistic in statistics %}
      <div class="col-12 col-sm-6 col-lg-6 list-item">
        <a href="{{ url_for('statistic.view', catalog=catalog.name, slug=slugify(statistic.title_de), name=statistic.name) }}">
          <code>{{ statistic.name }}</code> {{ statistic.title_de }}</a>
      </div>
      {% endfor %}
    </div>

    <hr>
    <h2 class="col-12"><i class="icon-list"></i> Attribute</h2>
    <p class="col-12">
      Statistiken setzen sich aus unterschiedlichen Attributen zusammen. Dazu gehören unter anderem 
      geographische Angaben zum erfassten Bereich, Sachmerkmale die Eigenschaften einer Beobachtung
      erfassen, Zeitmerkmale sowie die eigentlichen Messwerte, also die Ergebnisse der Erfassung.
    </p>
    {% for group in dimensions | groupby('measure_type_name') %}
      <h3 class="col-12">{{group.grouper}}</h3>
      <div class="col-12 row"> 
      {% for dimension in group.list %}
        <div class="col-12 col-sm-6 col-lg-6 list-item">
            
            <a href="{{ url_for('dimension.view', catalog=catalog.name, name=dimension.name) }}">
              <code>{{ dimension.name }}</code> {{ dimension.title_de }}</a>
        </div>
      {% endfor %}
      </div>
    {% endfor %}
    
  </div>
{% endblock %}

regenesis/templates/contact.html
{%extends "layout.html" %}

{% block description %}Kontaktinformationen zum ReGENESIS-Projekt, welches die Daten von Bundes- und Landesstatisikämtern in einfacher Form bereitstellt.{% endblock %}

{% block keywords %}Kontakt, Statistik, Regionalstatistik, Daten{% endblock %}

{% block title %}Kontakt{% endblock %}

{% block content %}
    <h2 class="page-title">Kontakt und Mitmachen</h2>
    <div class="row">
      <div class="col-12 col-sm-12 col-lg-6 content">
        <p>
            ReGENESIS wird als freie Software unter der MIT-Lizenz auf GitHub entwickelt. Wir freuen 
            uns über Fehlerbeschreibungen und Pull Requests für neue Funktionen.
        </p>
        <ul class="bullets">
            <li>Quellcode: <a href="https://github.com/pudo/regenesis"><i class="icon-github"></i> pudo/regenesis</a></li>
            <li>Bug tracker: <a href="https://github.com/pudo/regenesis/issues"><i class="icon-github"></i> pudo/regenesis:issues</a></li>
            <li><a href="http://pudo.org">Direkter Kontakt</a> zu Friedrich Lindenberg</li>
            
        </ul>
      </div>

      <div class="col-12 col-sm-12 col-lg-6 content">
        <p>
            Die Entwicklung von ReGENESIS wird durch ein OpenNews-Stipendium der Knight Foundation 
            und der Mozilla Foundation ermöglicht.
        </p>
        <p>
            <a href="http://mozillaopennews.org"><img src="/static/img/onlogo.png" alt="Knight-Mozilla OpenNews"></a>
        </p>
      </div>
  </div>
    <br>
    <p>
        Leider können die ReGENESIS-Entwickler Ihnen nicht als Rechercheservice für Daten
        bereit stehen, die nicht auf dieser Seite verfügbar sind. Wir bitten Sie, eine
        Suchmaschine zu benutzen bevor Sie sich an uns wenden.
    </p>

{% endblock %}

regenesis/templates/dimension/view.html
{%extends "layout.html" %}

{% block metatitle %}{{ catalog.title }}{% endblock %}

{% block title %}{{ dimension.title_de }}{% endblock %}

{% block content %}
  <h2 class="page-title">{{ dimension.measure_type | dimension_type_text }}:  {{ dimension.title_de }}</h2>
  <div class="row">
      <div class="col-12 col-sm-12 col-lg-3" id="sidebar">
        <h3>Hinweise zu <code>{{dimension.name}}</code></h3>
        <p>{{ dimension.definition_de | text }}</p>
      </div>

      <div class="col-12 col-sm-12 col-lg-9 content" id="page">
        <h3>Statistiken <small>In denen dieses Attribut aufgeführt wird</small></h3>
        {% for statistic in statistics %}
          <div class="col-12 col-sm-12 col-lg-12 list-item">
            <a href="{{ url_for('statistic.view', catalog=catalog.name, slug=slugify(statistic.title_de), name=statistic.name) }}">
              <code>{{ statistic.name }}</code> {{ statistic.title_de }}</a>
            </div>
        {% endfor %}
        <br/><br/>
        {%if has_values %}
          <h3>Wertebereich <small>{{ values | length }} Ausprägungen</small></h3>
          <table class="table table-striped table-condensed">
            {% for value in values %}
              <tr>
                <td><code>{{value.name}}</code></td>
                <td>{{value.title_de}}</td>
                <!--td>{{value.definition_de | text}}</td-->
              </tr>
            {% endfor %}
          </table>
        {% endif %}
      </div>
  </div>
{% endblock %}

regenesis/templates/faq.html
{%extends "layout.html" %}

{% block description %}Häufige Fragen zum ReGENESIS-Projekt, welches die Daten von Bundes- und Landesstatisikämtern in einfacher Form bereitstellt.{% endblock %}

{% block keywords %}FAQ, Statistik, Regionalstatistik, Daten{% endblock %}

{% block title %}Häufig gestellte Fragen{% endblock %}

{% block content %}
    <h2 class="page-title">Häufig gestellte Fragen zu ReGENESIS</h2>
    <div class="row">
      <div class="col-12 col-sm-12 col-lg-6 content">
        <h3>Was ist ReGENESIS?</h3>
        <p>
            ReGENESIS ist eine ständig aktualisierte Fassung der Statistiken von 
            Bund und Ländern. Die Tabellen werden dabei in Formaten angeboten,
            die für eine maschinelle Auswertung besonders gut geeignet sind.
        </p>
        <p>
            Statistikdaten von Bund und Ländern liegen zumeist als aggregierte 
            Berichte vor, die deren komplexer Tabellenaufbau kaum für
            eine automatische Auswertung oder die Nutzung in interaktiven Grafiken
            zugänglich sind.
        </p>
        <p>
            ReGENESIS bezieht seine Daten daher aus dem Massenexport verschiedener
            Instanzen des GENESIS-Systems, das vom Statistischen Bundesamt zur
            Verwaltung statistischer Daten entwickelt wird. So werden statistische 
            Daten im Rohformat, also sog. Datenquader, bereitgestellt.
        </p>

        <h3>Ist dies ein offizielles Angebot?</h3>
        <p>
            Nein. Die Daten entstammen aber einer amtlichen Quelle und sind im 
            Inhalt nicht verändert. 
        </p>

        <h3>Sind die Daten frei verfügbar?</h3>
        <p>
            Der <a href="http://www.gesetze-im-internet.de/urhg/__5.html">§5 des Urheberrechts</a>
            schliesst amtliche Statistiken vom Urheberrecht aus und stellt damit sicher, dass
            diese frei genutzt werden können. Die abgeleiteten Tabellen auf ReGENESIS werden
            ebenfalls ohne Einschränkungen unter den Bedingungen einer <a href="http://creativecommons.org/publicdomain/zero/1.0/">CC0-Lizenz</a> weitergegeben.
        </p>
        <p>
            Falls Sie dennoch auf ReGENESIS als Quelle verweisen wollen, dann können Sie das zum Beispiel 
            mit folgendem HTML-Snippet tun:

        </p>
        <div class="well mono">&lt;a href="http://regionalstatistik.de" target="_blank"&gt;Regionalstatistik.de&lt;/a&gt; via &lt;a href="http://regenesis.pudo.org/" target="_blank"&gt;ReGENESIS&lt;/a&gt;.</div>


      </div>

      <div class="col-12 col-sm-12 col-lg-6 content">
        <h3>Was sind Statistiken, Tabellen und Attribute?</h3>
        <p>
            Zur Speicherung der Daten verwenden die Ämter ein komplexes Datenmodell,
            welches sich für fortgeschrittene Analysen eignet. Im Sinne der
            Nutzbarkeit versucht ReGENESIS dieses zu vereinfachen und einige der
            verwendeten Fachbegriffe durch gängigere Wörter auszuwechseln:
        </p>
        <p>
            <strong>Statistiken</strong> sind Erhebungen, deren Erfassung gesetzlich 
            geregelt ist. Dabei werden verschiedene Merkmale erhoben, allerdings nicht
            vollständig veröffentlicht um die Anonymisierung der Daten nicht zu 
            gefährden.
        </p>
        <p>
            <strong>Tabellen</strong> (auch Datenquader) sind Auszüge aus einzelnen 
            Statistiken, die als Download angeboten werden. Sie enthalten zumeist nur
            einen Teil der Daten, die insgesamt für die Statistik erhoben wurden. Zudem
            werden Tabellen auf verschiedenen geographischen Niveaus angeboten, also 
            z.B. nach Bundesland, Kreis oder Gemeinde.
        </p>
        <p>
            <strong>Attribute</strong> (auch Merkmale, Messwerte, Dimensionen) sind 
            mit den Spalten einer Tabelle vergleichbar. Sie beschreiben z.B. wann, wo 
            und in welcher Untergruppe welche Werte beobachtet wurden.
        </p>

        <h3>Wie oft werden die Daten aktualisiert?</h3>
        <p>
            Im Regelbetrieb werden wie Daten wöchtenlich aus den ursprünglichen 
            Datenquellen aktualisieren.
        </p>

        <h3>Gibt es eine Programmierschnittstelle (API)?</h3>
        <p>
            ReGENESIS bietet eine HTTP-basierte API an, die Daten im JSON-Format
            bereitstellt. Damit können Statistiken aus ReGENESIS direkt in
            Visualisierungen eingebunden werden, die somit immer aktuell bleiben.
            <a href="/api.html">Mehr Informationen...</a>
        </p>
      </div>
  </div>

{% endblock %}

regenesis/templates/index.html
{%extends "layout.html" %}

{% block title %}
  ReGenesis
{% endblock %}

{% block metatitle %}
  ReGenesis
{% endblock %}

{% block content %}
  <div id="page" class="row">
    <div class="col-12">
      Aktuelle Datenbanken: <a href="/regional/index.html">Regionalstatistik</a>
    </div>
  </div>
{% endblock %}

{% block script %}
  <script>
    $(function() {
        document.location.href = '/regional/index.html';
    });
  </script>
{% endblock %}

regenesis/templates/layout.html
<!DOCTYPE html>
<html lang="de">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>{% block title %}Statistik-Viewer{% endblock %} - Statistiken von Bund und Ländern</title>
    <meta name="description" content="{% block description %}Maschinenlesbare Datensätze aus dem Fundus der deutschen Bundes- und Regionalstatistik{% endblock %}">
    <meta name="keywords" content="{% block keywords %}Statistik, Daten, Tabellen, Regionalstatistik, Destatis{% endblock %}">
    
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0-rc1/css/bootstrap.min.css" rel="stylesheet">
    <link href="//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css" rel="stylesheet">
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700' rel='stylesheet' type='text/css'>
    <link href="/static/css/style.css" rel='stylesheet' type='text/css'>

    <!-- Beautification -->
    <link rel="shortcut icon" href="http://assets.pudo.org/img/opennews-favicon.ico" type="image/x-icon" />
  </head>
  <body class="body-data">
    <div class="navbar">
      <div class="container">
        <a class="navbar-brand" href="/index.html">ReGENESIS</a>
        <ul class="nav navbar-nav pull-right">
          <li><a href="/regional/index.html">Regionalstatistik</a></li>
          <li><a href="/faq.html">FAQ</a></li>
          <li><a href="/contact.html">Kontakt &amp; Mitmachen</a></li>
        </ul>
      </div>
    </div>

    <div id="airlock" class="container show-grid">
      {% block content %}This page intentionally left blank{% endblock %}
    </div>

    <footer class="container hidden-print">
      <i class="icon-github"></i> <a href="http://github.com/pudo/regenesis">code</a>
      von <i class="icon-twitter"></i> <a href="http://twitter.com/pudo">pudo</a>,
      dank <a href="http://mozillaopennews.org">Knight-Mozilla OpenNews</a>.
    </footer>

    <script src="http://code.jquery.com/jquery-1.10.1.min.js"></script>
    {% block script %}{% endblock %}
    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-34039573-5', 'pudo.org');
      ga('send', 'pageview');

    </script>
  </body>
</html>

regenesis/templates/statistic/view.html
{%extends "layout.html" %}

{% block description %}{{ description_text }}{% endblock %}

{% block keywords %}{{ keywords_text }}{% endblock %}

{% block title %}{{ statistic.title_de }}{% endblock %}


{% block content %}
  <h2 class="page-title">{{ statistic.title_de }}</h2>
  <div class="row">
      <div class="col-12 col-sm-12 col-lg-3" id="sidebar">
        <ul class="entries">
            <li><i class="icon-tag"></i> Kennung: <code>{{statistic.name}}</code></li>
            <li><i class="icon-building"></i> Art: <a href="{{desc.legal}}">{{desc.type}}</a></li>
            <li><i class="icon-calendar"></i> Erhebung: {{desc.periodicity}}, {{desc.stag}}</li>
            <li><i class="icon-map-marker"></i> Regionalebene: {{desc.geo}}</li>
        </ul>
        
      </div>

      <div class="col-12 col-sm-12 col-lg-9 content" id="page">
        <h3>Methodische Hinweise</h3>
        <p>{{desc.method | wraptext}}</p>

        <h3>Tabellen</h3>
        <p>Die untenstehenden Tabellen enthalten die Messungen zur zur Statistik <em>{{ statistic.title_de }}</em>. Sie unterscheiden sich in ihrer geographischen Granularität sowie den enthaltenen Attributen.</p>
        {% if has_common and False %}
            <h4>Gemeinsame Attribute</h4>
            <p>In allen Tabellen dieser Statistik werden die folgenden Attribute ausgewiesen:</p>
            <ul>
                {% for dim in common %}
                    <li><code>{{dim.dim_name}}</code> {{dim.dim_title_de}}</li>
                {% endfor %}
            </ul>
        {% endif %}
        {% for group in cubes | groupby('admlevel') %}
            <h4>{{group.grouper[1]}} <small><a href="{{ url_for('dimension.view', catalog=catalog.name, name=group.grouper[2]) }}"><i class="icon-info-sign"></i></a></small></h4>
            {% for cube in group.list %}
            <div class="list-item">
                <div class="panel">
                    <div class="panel-heading"><i class="icon-table"></i> Tabelle <code>{{cube.name}}</code>
                    <span class="pull-right">Stand: {{cube.stand}}</span></div>
                    <ul class="list-group">
                        {% for d in cube.dimensions %}{% if d.show %}
                            <li class="list-group-item"><i class="icon-columns"></i> <a href="{{ url_for('dimension.view', catalog=catalog.name, name=d.dim_name) }}"><code>{{d.dim_name}}</code> {{ d.dim_title_de }}</a> ({{d.type_text}})</li>
                        {% endif %}{% endfor %}    

                    </ul>
                    <div class="btn-group">
                        <a href="/data/{{statistic.name}}/{{cube.name}}/{{statistic.title_de | slugify }}-{{cube.name}}-labeled.csv" 
                            class="btn btn-default"><i class="icon-download"></i>
                            Rechercheversion <span class="badge">CSV</span></a>
                        <a href="/data/{{statistic.name}}/{{cube.name}}/{{statistic.title_de | slugify }}-{{cube.name}}-raw.csv" 
                            class="btn btn-default"><i class="icon-download"></i>
                            Rohversion <span class="badge">CSV</span></a>
                        <a href="{{API}}/cube/{{cube.name}}/aggregate" 
                            class="btn btn-default"><i class="icon-cloud"></i>
                            API-Endpunkt <span class="badge">JSON</span></a>
                        <a href="/api.html" 
                            class="btn btn-default"><i class="icon-question-sign"></i>
                            API-Doku</a>
                    </div>
                </div>
            </div>
            {% endfor %}
        {% endfor %}

        
      </div>
  </div>
{% endblock %}